language: scala
jdk: oraclejdk8
scala:
   - 2.11.8

sudo: false

# Build only master and version tags
branches:
  only:
    - master
    - /^v[0-9]/

before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
  
cache:
  directories:
    - $HOME/.sbt
    - $HOME/.ivy2/cache

script:
  - sbt coverage test coverageReport coverageAggregate
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
